# Composite actions
# - intro
#   https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# - syntax
#   https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
# - comparison with reusable workflows
#   https://docs.github.com/en/actions/sharing-automations/avoiding-duplication#key-differences-between-reusable-workflows-and-composite-actions
name: Generate unique ID

description: Generate a unique ID useful in artifact names

inputs:
  set-env-context:
    description: "Create environment variables in addition? This allows use of `env.unique-id` instead of the longer `steps.<step_id>.outputs.unique-id` in following steps."
    default: 'false' # string expected
    required: false

outputs:
  os:
    description: "Context `runner.os` in lowercase"
    value: ${{ steps.run.outputs.os }}
  unique-id:
    description: "A unique id per commit and run attempt, `<sha1-prefix>[-<run>]`"
    value: ${{ steps.run.outputs.unique-id }}

runs:
  using: "composite"
  steps:
    - name: main
      id: run
      shell: bash
      run: |
        OS="$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
        SHA1_SHORT="$(git rev-parse --short HEAD)"
        if [[ "${{ github.run_attempt }}" -eq 1 ]]; then
          UNIQ_ID="$SHA1_SHORT"
        else
          UNIQ_ID="$SHA1_SHORT-${{ github.run_attempt }}"
        fi

        echo "os=$OS"             >> "$GITHUB_OUTPUT"
        echo "unique-id=$UNIQ_ID" >> "$GITHUB_OUTPUT"

        if [[ "${{ inputs.set-env-context }}" == "true" ]]; then
          echo "os=$OS"             >> "$GITHUB_ENV"
          echo "unique-id=$UNIQ_ID" >> "$GITHUB_ENV"
        fi
