# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Generate unique ID

inputs:
  set-env-context:
    description: "Create environment variables in addition? This allows use of `env.unique-id` instead of the longer `steps.<step_id>.outputs.unique-id` in following steps."
    default: false
    type: boolean
outputs:
  os:
    description: "Context `runner.os` in lowercase"
    value: ${{ steps.run.outputs.os }}
  unique-id:
    description: "A unique id per commit and run attempt, `<sha1-prefix>[-<run>]`"
    value: ${{ steps.run.outputs.unique-id }}

runs:
  using: "composite"
  steps:
    - name: main
      id: run
      shell: bash
      run: |
        OS="$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')"
        SHA1_SHORT="$(git rev-parse --short HEAD)"
        if [[ "${{ github.run_attempt }}" -eq 1 ]]; then
          UNIQ_ID="$SHA1_SHORT"
        else
          UNIQ_ID="$SHA1_SHORT-${{ github.run_attempt }}"
        fi

        echo "os=$OS"             >> "$GITHUB_OUTPUT"
        echo "unique-id=$UNIQ_ID" >> "$GITHUB_OUTPUT"

        if [[ "${{ inputs.set-env-context }}" != 'false' ]]; then
          echo "os=$OS"             >> "$GITHUB_ENV"
          echo "unique-id=$UNIQ_ID" >> "$GITHUB_ENV"
        fi
