# https://github.com/rhysd/actionlint/issues/630

on:
  push

jobs:
  phpunit-tests:
    name: PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        php: [ '8.3', '8.4', '8.5' ]
        include:
          # Include jobs that test with memcached.
          - os: [ 'ubuntu-latest' ]
            php: [ '8.2' ]
        exclude:
          - os: [ 'macos-latest' ]
            php: '8.3'
    steps:
      - run: |
          echo os: "${{ matrix.os }}"
          echo php: "${{ matrix.php }}"
