name: Test LaTeX

on: 
  push:
    branches-ignore:
      - 'self/**' # "**" also matches remaining "/"
    paths:
      - 'latex-examples'
      - '.github/workflows/latex-three-os.yml'
  pull_request:
    paths:
      - 'latex-examples'
      - '.github/workflows/latex-three-os.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-on-three-os:
    strategy:
      matrix:
        # as of 2023-12-02, macos-latest still uses macos-12
        # see https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # and https://github.com/actions/runner-images/issues/7508
        # macos-13 is also used in brew-bump-pr.yml
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install texlive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            xetex
          update-all-packages: true

      - name: Generate unique ID
        uses: ./.github/actions/unique-id
        with:
          set-env-context: true

      - name: Run example(s)
        working-directory: latex-examples
        run: |
          for file in $(ls *.tex); do
            for engine in pdflatex lualatex xelatex; do
              $engine -jobname=${file/%.tex}-${{ env.os }}-${engine/la/} $file

              # # use "%0A" to throw a multiline warning
              # # https://github.com/actions/toolkit/issues/193#issuecomment-605394935
              # log_filtered=$(\
              #   grep -rh "\[debug\] " *.log | \
              #   awk 'BEGIN {RS=""}{gsub(/\n/,"%0A",$0); print $0}' \
              # )
              # # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message
              # echo "::warning file=$file-$engine*.log,line=1,col=1,endColumn=2::$log_filtered"
            done
          done

      - name: Archive per OS
        uses: actions/upload-artifact@v4
        with:
          name: latex-examples-${{ env.unique-id }}
          path: latex-examples
