name: Test LaTeX - docker

on:
  push:
    branches-ignore:
      - 'self/**' # "**" also matches remaining "/"
    paths:
      - 'latex-examples'
      - '.github/actions/unique-id'
      - '.github/workflows/latex-docker.yml'
  pull_request:
    paths:
      - 'latex-examples'
      - '.github/actions/unique-id'
      - '.github/workflows/latex-docker.yml'
  workflow_dispatch:

jobs:
  run-in-docker:
    runs-on: ubuntu-latest
    container:
      # https://gitlab.com/islandoftex/images/texlive

      image: registry.gitlab.com/islandoftex/images/texlive:TL2022-2022-11-06-full
    defaults:
      run:
        # The default shell for run steps inside a container is sh instead of bash.
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer
        shell: bash

    steps:
      - name: Globally opt-out Git security check
        run: |
          git config --global safe.directory "*"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout tcolorbox@v6.2.0
        uses: actions/checkout@v4
        with:
          repository: T-F-S/tcolorbox
          ref: v6.2.0
          token: ${{ github.token }}
          path: tcolorbox
          sparse-checkout: tex

      - name: Checkout tikzfill@1.0.1
        uses: actions/checkout@v4
        with:
          repository: T-F-S/tikzfill
          ref: v1.0.1
          token: ${{ github.token }}
          path: tikzfill

      - name: Generate unique ID
        uses: ./.github/actions/unique-id
        with:
          set-env-context: true

      - name: Run example(s)
        run: |
          export TEXMFHOME="$(realpath ./tcolorbox):$(realpath ./tikzfill)"
          cd latex-examples
          for file in *.tex; do
            for engine in pdflatex lualatex xelatex; do
              echo -e "\n\n"
              echo "========================"
              echo "  $engine $file"
              echo "========================"
              echo -e "\n\n"
              # e.g., executes
              #   pdflatex -interaction=nonstopmode -jobname="simple-pdftex" simple.tex
              $engine \
                -interaction=nonstopmode \
                -jobname="${file/%.tex}"-"${engine/la/}" \
                -shell-escape \
                "$file"
            done
          done

      - name: Debug with tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latex-examples-docker-${{ env.unique-id }}
          path: latex-examples
