name: Test LaTeX - docker

on:
  push:
    paths: &path-filter
      - 'latex-examples/**'
      - '.github/actions/unique-id/**'
      - '.github/workflows/latex-docker.yml'
  pull_request:
    branches: # the base branch
      - 'main'
    paths: *path-filter
    types:
      # added "ready_for_review" activity type
      [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:

jobs:
  run-in-docker:
    runs-on: ubuntu-latest
    container:
      # https://gitlab.com/islandoftex/images/texlive
      ## https://gitlab.com/islandoftex/images/texlive/container_registry/573747
      ## latex 2021-11-15
      # image: registry.gitlab.com/islandoftex/images/texlive:TL2021-2021-11-14-04-43
      ## latex 2022-11-01
      # image: registry.gitlab.com/islandoftex/images/texlive:TL2022-2022-11-06-full
      ## latest
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    defaults:
      run:
        # The default shell in a container is `sh` instead of `bash`.
        # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer
        shell: bash

    steps:
      - name: Update TeX Live
        id: tlmgr-update
        run: |
          tlmgr update --self --all

      # `actions/checkout` default input `set-safe-directory: true` doesn't work
      # for containers.
      # see for example https://github.com/actions/checkout/issues/766
      - name: Globally opt-out Git security check
        # `git config set` needs Git v2.46.0 (2024-07-29) or later
        run: |
          git config --global safe.directory "*"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate unique ID
        uses: ./.github/actions/unique-id
        with:
          set-env-context: true

      - name: Run example(s)
        working-directory: latex-examples
        run: |
          for file in *.tex; do
            for engine in pdflatex lualatex xelatex; do
              # e.g., executes
              #   pdflatex -jobname=simple-pdftex -shell-escape simple.tex
              $engine \
                -jobname="${file/%.tex}"-"${engine/la/}" \
                -shell-escape \
                "$file"
            done
          done

      # run `touch continue` in GITHUB_WORKSPACE to continue
      # https://github.com/mxschmitt/action-tmate/tree/v3/?tab=readme-ov-file#continue-a-workflow
      - name: Debug via SSH
        if: steps.tlmgr-update.outcome == 'success' && failure()
        timeout-minutes: 15
        uses: mxschmitt/action-tmate@v3

      - name: Archive
        # "!" is reserved in YAML
        # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
        # > Explicit typing is denoted with a tag using the exclamation point (“!”) symbol.
        # https://yaml.org/spec/1.2.2/#24-tags
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: latex-examples-docker-${{ env.unique-id }}
          path: latex-examples
