name: Test LaTeX - native

on:
  push:
    # Starting from Aug, 2025, yaml anchors are supported in workflow files.
    # https://github.com/actions/runner/issues/1182
    # A yaml anchor denoted by &<name> can then be aliased (repeatedly)
    # by *<name>.
    # https://yaml.org/spec/1.2.2/#692-node-anchors
    # https://yaml.org/spec/1.2.2/#71-alias-nodes
    paths: &path-filter
      - 'latex-examples/**'
      - '.github/actions/unique-id/**'
      - '.github/workflows/latex-native.yml'
  pull_request:
    branches: # the base branch
      - 'main'
    paths: *path-filter
    types:
      # added "ready_for_review" activity type
      [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  run-on-native-os:
    strategy:
      matrix:
        # According to https://github.com/github/roadmap/issues/986,
        # > macos-latest label will incrementally transition from macOS 14 to
        # > macOS 15 beginning November 2024 and will conclude before the end
        # > of December 2024
        # Note macos-14 runs on Arm64 architecture.
        os: [ubuntu-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install texlive
        uses: TeX-Live/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            xetex
          update-all-packages: true

      - name: Generate unique ID
        uses: ./.github/actions/unique-id
        with:
          set-env-context: true

      - name: Run example(s)
        working-directory: latex-examples
        run: |
          for file in *.tex; do
            for engine in pdflatex lualatex xelatex; do
              # e.g., ececutes
              #   pdflatex -jobname=simple-linux-pdftex -shell-escape simple.tex
              $engine \
                -jobname="${file/%.tex}"-${{ env.os }}-"${engine/la/}" \
                -shell-escape \
                "$file"

              # # use "%0A" to throw a multiline warning
              # # https://github.com/actions/toolkit/issues/193#issuecomment-605394935
              # log_filtered=$(\
              #   grep -rh "\[debug\] " *.log | \
              #   awk 'BEGIN {RS=""}{gsub(/\n/,"%0A",$0); print $0}' \
              # )
              # # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-warning-message
              # echo "::warning file=$file-$engine*.log,line=1,col=1,endColumn=2::$log_filtered"
            done
          done

      # run `touch continue` in GITHUB_WORKSPACE to continue
      # https://github.com/mxschmitt/action-tmate/tree/v3/?tab=readme-ov-file#continue-a-workflow
      - name: Setup tmate session
        if: failure()
        timeout-minutes: 15
        uses: mxschmitt/action-tmate@v3

      - name: Archive per OS
        # "!" is reserved in YAML
        # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
        # > Explicit typing is denoted with a tag using the exclamation point (“!”) symbol.
        # https://yaml.org/spec/1.2.2/#24-tags
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: latex-examples-${{ env.os }}-${{ env.unique-id }}
          path: latex-examples
