name: Test LaTeX
on: 
  - push
  - workflow_dispatch

jobs:
  run-on-three-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install texlive
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            scheme-basic
            array
            l3experimental

      - name: Set env vars
        shell: bash
        run: |
          # env.os_null
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            OS_NULL="nul"
          else
            OS_NULL="/dev/null"
          fi
          echo "os_null=$OS_NULL" >> $GITHUB_ENV
          # env.artifact_id
          SHORT_OS=${{ matrix.os }}
          SHORT_OS=${SHORT_OS/-latest/}
          SHORT_SHA1=$(git rev-parse --short HEAD)
          if [[ "${{ github.run_attempt }}" -eq 1 ]]; then
            ID="$SHORT_OS-$SHORT_SHA1"
          else
            ID="$SHORT_OS-$SHORT_SHA1-${{ github.run_attempt }}"
          fi
          echo "artifact_id=$ID" >> $GITHUB_ENV

      - name: Run example(s)
        shell: bash
        working-directory: latex-examples
        run: |
          # ENGINES=("pdflatex" "lualatex")
          ENGINES=("pdflatex")
          for engine in ${ENGINES[@]}; do
            $engine l3benchmark-gh1182*.tex > "${{ env.os_null }}"
            # use "%0A" to throw a multiline warning
            # https://github.com/actions/toolkit/issues/193#issuecomment-605394935
            log_filtered=$(\
              grep -rh -B 3 "seconds" *.log | \
              awk 'BEGIN {RS=""}{gsub(/\n/,"%0A",$0); print $0}' \
            )
            # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message
            echo "::warning file=l3benchmark-gh1182-$engine*.log,line=1,col=1,endColumn=2::$log_filtered"
          done

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: latex-examples-${{ env.artifact_id }}
          path: latex-examples
