name: Test mise-action

permissions:
  contents: read

on:
  push:

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup mise
      uses: jdx/mise-action@v4

    - name: Check mise tool
      run: |
        typos --version

    - name: Run mise tasks
      run: |
        mise run lint:typos
