name: Batch Release
on: push

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello > job-a.txt
    - uses: actions/upload-artifact@v2
      with:
        name: job-a
        path: job-a.txt
  job-b:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello > job-b.txt
    - uses: actions/upload-artifact@v2
      with:
        name: job-b
        path: job-b.txt
  release:
    runs-on: ubuntu-latest
    needs: [job-a, job-b]
    steps:
    - uses: actions/download-artifact@v2

    - name: Display structure of downloaded files
      run: |
        FILE_LIST=$(find . -depth 2)
        echo "file_list<<EOF" >> $GITHUB_ENV
        echo "$FILE_LIST" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        # debug
        echo $FILE_LIST
        echo $GITHUB_ENV

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.file_list }}

