name: reusable callee

run-name: reusable callee (${{ github.event_name }})

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs: &inputs
      runs-on:
        description: 'The type of runner to run the job on'
        default: 'ubuntu-latest'
        required: false
        type: string
      is-workflow_call:
        description: 'Whether this workflow is called by another workflow'
        default: false
        required: false
        type: boolean
  workflow_call:
    inputs: *inputs

jobs:
  callee-job:
    # distinguish between normal and inherited `workflow_dispatch` events
    name: |-
      Callee${{ case(
        github.event_name == 'workflow_dispatch' && github.event.workflow == '.github/workflows/reusable-callee.yml',
        format(' ({0})', inputs.runs-on),
        ''
      ) }}
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    defaults:
      run:
        shell: bash

    steps:
      - run: echo "Hello from reusable callee"

      - name: dump github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: dump job context
        run: echo "$JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}

      # `job.workflow_file_path` is not available on GHES
      # see https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#job-context
      - name: dump selected context properties
        run: |
          echo "github.event_name=${{ github.event_name }}"

          echo "github.workflow_ref=${{ github.workflow_ref }}"
          echo "job.workflow_ref=${{ job.workflow_ref }}"

          echo "github.event.workflow=${{ github.event.workflow }}"
          echo "job.workflow_file_path=${{ job.workflow_file_path }}"

          {
            echo "github.event_name=${{ github.event_name }}"
            echo "inputs.workflow_call=${{ inputs.is-workflow_call || 'false' }}"
            echo "github.workflow_ref == job.workflow_ref ${{ github.workflow_ref == job.workflow_ref }}"
            echo "job.workflow_file_path == '.github/workflows/reusable-callee.yml' ${{ job.workflow_file_path == '.github/workflows/reusable-callee.yml' }}"
          } >> "$GITHUB_STEP_SUMMARY"

          is_workflow_call="${{ inputs.is-workflow_call || 'false' }}"
          is_workflow_refs_match="${{ github.workflow_ref == job.workflow_ref }}"
          is_workflow_file_path_match="${{ job.workflow_file_path == '.github/workflows/reusable-callee.yml' }}"

          exit_code=0
          if [[ "$is_workflow_call" == "$is_workflow_refs_match" ]]; then
            echo "::error title=unexpected (job|workflow).workflow_ref props::inputs.is-workflow_call=$is_workflow_call, github.workflow_ref=${{ github.workflow_ref }}, job.workflow_ref=${{ job.workflow_ref }}"
            exit_code=1
          fi
          if [[ "$is_workflow_file_path_match" != "true" ]]; then
            echo "::error title=unexpected job.workflow_file_path::inputs.is-workflow_call=$is_workflow_call, job.workflow_file_path=${{ job.workflow_file_path }}"
            exit_code=1
          fi
          exit $exit_code
