name: reusable callee

on:
  # push:
  # pull_request:
  workflow_dispatch:
    inputs: &inputs
      runs-on:
        description: 'The type of runner to run the job on'
        default: 'ubuntu-latest'
        required: false
        type: string
  workflow_call:
    inputs: *inputs

jobs:
  callee-job:
    # distinguish between normal and inherited `workflow_dispatch` events
    name: |-
      Callee${{ case(
        github.event_name == 'workflow_dispatch' && github.event.workflow == '.github/workflows/reusable-callee.yml',
        format(' ({0})', inputs.runs-on),
        ''
      ) }}
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    defaults:
      run:
        shell: bash

    steps:
      - run: echo "Hello from reusable callee"

      - name: dump github context
        run: echo "${{ toJSON(github) }}"

      - name: dump job context
        run: echo "${{ toJSON(job) }}"

      # `job.workflow_file_path` is not available on GHES
      # see https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#job-context
      - run: |
          echo "github.event.workflow=${{ github.event.workflow }}"
          echo "job.workflow_file_path=${{ job.workflow_file_path }}"
        if: github.event_name == 'workflow_dispatch'
