name: reusable callee

on:
  # push:
  # pull_request:
  workflow_dispatch:
    inputs: &inputs
      runs-on:
        description: 'The type of runner to run the job on'
        default: 'ubuntu-latest'
        required: false
        type: string
  workflow_call:
    inputs: *inputs

jobs:
  callee-job:
    name: Callee [${{ inputs.runs-on || 'ubuntu-latest' }}]
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - run: echo "Hello from reusable callee"
