name: reusable caller

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  caller-job:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    name: Caller
    runs-on: ${{ matrix.runs-on }}
    steps:
      # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-using-an-action-in-the-same-repository-as-the-workflow-at-the-running-commit-recommended
      - uses: $/.github/actions/reusable
