name: Test GitHub Actions

on:
  push:
    paths:
      - '.github/workflows/test-github-actions.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/test-github-actions.yml'
    types:
      # added "ready_for_review" activity type
      [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:
    inputs:
      runner:
        description: Name of runner image
        required: false
        default: macos-latest
        type: string
      commands:
        description: Commands to run
        required: false
        default: ""
        type: string

jobs:
  test:
    name: Hello

    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v7

      - name: Run dummy commands
        run: |
          ${{ inputs.commands || 'echo "Hello Github Actions"' }}

      # run `cd "$GITHUB_WORKSPACE" && touch continue` to continue
      # https://github.com/owenthereal/action-upterm#continue-a-workflow
      - name: Debug with SSH
        # to respond to cancellation (make the if-expression re-evaluates
        # to false), we need to check `cancelled()` first
        # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-cancellation
        if: ${{ !cancelled() && failure() }}
        uses: owenthereal/action-upterm@v2
        with:
          wait-timeout-minutes: 5
