name: Test cli/cli#5268

on:
  # push:
  #   paths:
  #     - '.github/workflows/test-github-actions.yml'
  # pull_request:
  #   branches-ignore:
  #     - 'self/**' # "**" also matches remaining "/"
  #   paths:
  #     - '.github/workflows/test-github-actions.yml'
  #   types:
  #     # added type of activity "ready_for_review"
  #     [opened, ready_for_review, reopened, synchronize]
  workflow_dispatch:
    inputs:
      timeout-minutes:
        description: Max time of the tmate step
        required: false
        # Max time of a job is 6h
        # https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits
        default: 120
        type: number
      runner:
        description: Name of runner image
        required: false
        # full list of GitHub-hosted runners
        #     https://github.com/actions/runner-images
        default: ubuntu-latest
        type: string

jobs:
  test:
    name: Hello

    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Run dummy commands
        run: |
          echo "Hello GitHub Actions"
