name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Bash commands to run'
        required: false

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello from workflow_dispatch placeholder"
          echo "\`github.event_name=${{ github.event_name }}\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Run custom commands from `inputs.run`
        if: inputs.run
        run: |
          ${{ inputs.run }}
